// Default values for HeroSlider component
export const HERO_SLIDER_DEFAULTS = {
  autoPlay: true,
  interval: 5000,
  maxWidth: "60%",
  styles: {
    // NEW: CTA Button Padding Defaults

    titleFontSize: {
      xs: "0.8rem",
      sm: "1.5rem",
      md: "2rem",
      lg: "2.5rem",
      xl: "4rem",
    },
    titleColor: "#FFFFFF",
    titleFontFamily: "sans-serif",
    titleFontWeight: "700",
    titleMarginBottom: { xs: 2, sm: 6, md: 8, lg: 10, xl: 12 },
    titleMarginLeft: 0,
    descriptionFontSize: {
      xs: "0.4rem",
      sm: "0.6rem",
      md: "0.8rem",
      lg: "1rem",
      xl: "1.6rem",
    },
    descriptionColor: "#FFFFFF",
    descriptionFontFamily: "sans-serif",
    descriptionFontWeight: "400",
    descriptionMarginBottom: { xs: 2, sm: 6, md: 8, lg: 10, xl: 12 },
    descriptionMarginLeft: 0,
    ctaButtonColor: "#000",
    ctaButtonBg: "#FFD700",
    ctaButtonHoverBg: "#FFFFFF",
    ctaButtonFontSize: {
      xs: "0.2rem",
      sm: "0.4rem",
      md: "0.6rem",
      lg: "1rem",
      xl: "1.4rem",
    },
    ctaButtonFontWeight: "700",
    ctaButtonBorderRadius: "4px",

    // NEW: CTA Button Padding defaults
    ctaButtonPadding: "8px 16px",
    ctaButtonPaddingX: 0,
    ctaButtonPaddingY: 0,

    overlayBackground:
      "linear-gradient(to right, rgba(0,0,0,1), rgba(0,0,0,0.8), rgba(0,0,0,0.1))",
    paddingLeft: 0,
    spacingBetweenText: 4,
    responsivePaddingLeft: { xs: 6, sm: 8, md: 10, lg: 12, xl: 16 },
  },
  imageKeySelect: "imgFeaturedCarousel16x6",
  imageKeyText: "",
  imageKeySrc: "",
  aspectRatio: "16:6" as const,
  secondaryImage: {
    show: false,
    keySelect: "",
    keyText: "",
    src: "",
    position: "bottom-right" as const,
    width: "40px",
    height: "40px",
    offsetX: 0,
    offsetY: 0,
  },
  arrowStyle: {
    leftArrowIcon: "",
    rightArrowIcon: "",
    backgroundColor: "transparent",
    hoverBackgroundColor: "transparent",
    color: "#ffffff",
    hoverColor: "#ffffff",
    size: "30px",
    borderRadius: "50%",
    padding: 1,
    leftOffsetX: 16,
    leftOffsetY: 0,
    rightOffsetX: 16,
    rightOffsetY: 0,
    hoverScale: 1.2,
  },
  // NEW: Pagination Style Defaults
  paginationStyle: {
    show: true,
    position: "bottom-center" as const,
    offsetX: 0,
    offsetY: 20, // 20px from bottom
    dotSize: "12px",
    dotSpacing: "8px",
    dotColor: "rgba(255,255,255,0.5)",
    activeDotColor: "#ffffff",
    dotBorderRadius: "50%",
    dotOpacity: 0.5,
    activeDotOpacity: 1,
    hoverDotColor: "rgba(255,255,255,0.8)",
    dotBorder: "none",
    activeDotBorder: "none",
    backgroundColor: "transparent",
    containerPadding: "8px 16px",
    containerBorderRadius: "20px",
  },
};
