// Default values for Card component
export const CARD_DEFAULTS = {
  aspectRatio: "16:9",
  objectFit: "cover",
  borderRadius: "16px",
  tag: {
    color: "white",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: "16px",
    fontSize: "0.75rem",
    fontWeight: 600,
    margin: "0",
    zIndex: 2,
  },
  icon: {
    color: "white",
    backgroundColor: "transparent",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "transparent",
    borderRadius: "50%",
    hoverBackgroundColor: "transparent",
    size: 20,
    margin: "0",
    zIndex: 2,
  },
  secondaryImage: {
    position: "top-right",
    size: { width: "auto", height: "auto" },
    opacity: 1,
    zIndex: 1,
    margin: "0",
    objectFit: "contain",
    blend: "normal",
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "left center",
    backgroundColor: "rgba(0, 0, 0, 0.1)",
    mainImageWidth: "100%",
    mainImageHeight: "100%",
    mainImageBorderRadius: "0",
    mainImageOpacity: 1,
  },
  card: {
    maxWidth: "100%",
    transition: "transform 0.3s ease, box-shadow 0.3s ease",
    transformOrigin: "center center",
  },
  cardContent: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 2,
    px: 2,
    py: 1.5,
    color: "white",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    background:
      "linear-gradient(180deg, rgba(12, 25, 64, 0.2) 0%,  #0C1940 50%)",

    transition: "opacity 0.3s ease",
    opacity: 0,
    hoverOpacity: 1,
  },
  titleTypography: {
    fontWeight: 600,
    fontSize: "1.1rem",
    mb: 0.5,
    lineHeight: 1.2,
    pt: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    gutterBottom: true,
    variant: /** @type {"h6"} */ "h6",
    component: "div",
    noWrap: true,
    WebkitLineClamp: 1,
    WebkitBoxOrient: "vertical",
    display: "-webkit-box",
  },
  summaryTypography: {
    fontSize: "0.7rem",
    lineHeight: 1.2,
    opacity: 0.9,
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  episodeTitle: {
    fontSize: "1rem",
    fontWeight: 600,
    mt: 0.5,
    mb: 3,
    color: "#fff",
    variant: /** @type {"h6"} */ "h6",
    component: "div",
  },
  episodeSummary: {
    variant: /** @type {"body2"} */ "body2",
    fontSize: "0.8rem",
    fontWeight: 400,

    color: "#fff",
    lineHeight: 1.4,
  },
};
