export const HERO_Section_DEFAULTS = {
  maxWidth: "60%",
  backgroundFallbackColor: "#f0f0f0",
  fallbackCtaText: "Watch Now",
  hoverCursor: "pointer",
  imageSize: "640",
  descriptionLineClamp: 4,

  styles: {
    showTitle: false,
    titleFontSize: {
      xs: "0.8rem",
      sm: "1.5rem",
      md: "2rem",
      lg: "2.5rem",
      xl: "4rem",
    },
    titleColor: "#FFFFFF",
    titleFontFamily: "sans-serif",
    titleFontWeight: "700",
    titleMarginBottom: { xs: 2, sm: 6, md: 8, lg: 10, xl: 12 },
    titleMarginLeft: 0,
    descriptionFontSize: {
      xs: "0.4rem",
      sm: "0.6rem",
      md: "0.8rem",
      lg: "1rem",
      xl: "1.6rem",
    },
    descriptionColor: "#FFFFFF",
    descriptionFontFamily: "sans-serif",
    descriptionFontWeight: "400",
    descriptionMarginBottom: { xs: 0, sm: 0, md: 0, lg: 0, xl: 0 },
    descriptionMarginLeft: 0,
    ctaButtonColor: "#000",
    ctaButtonBg: "#FFD700",
    ctaButtonHoverBg: "#FFFFFF",
    ctaButtonFontSize: {
      xs: "0.2rem",
      sm: "0.4rem",
      md: "0.6rem",
      lg: "1rem",
      xl: "1.4rem",
    },
    ctaButtonFontWeight: "700",
    ctaButtonBorderRadius: "4px",
    ctaMarginBottom: { xs: 2, sm: 6, md: 8, lg: 10, xl: 12 },
    secondaryImageMarginTop: { xs: 3, md: 8 },
    secondaryImageMarginBottom: { xs: 6, md: 16, xl: 30 },
    ctaButtonPadding: "8px 16px",
    ctaButtonPaddingX: 0,
    ctaButtonPaddingY: 0,
    overlayBackground:
      "linear-gradient(to right, rgba(0,0,0,1), rgba(0,0,0,0.8), rgba(0,0,0,0.1))",
    paddingLeft: 0,
    spacingBetweenText: 4,
    responsivePaddingLeft: { xs: 6, sm: 8, md: 10, xl: 12 },

    descriptionKey: "shortDescription",
  },

  imageKeySelect: "imgFeaturedCarousel6x9",
  imageKeyText: "",
  imageKeySrc: "",
  aspectRatio: "16:6" as const,

  secondaryImage: {
    show: true,
    keySelect: "imgSeriesLogo",
    keyText: "",
    src: "",
    position: "bottom-right" as const,
    width: "400px",
    height: "120px",
    offsetX: 0,
    offsetY: 0,
  },
};
